# Generated by Django 4.1.7 on 2023-03-04 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.URLField()),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('floor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('storey', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('yard_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bedroom', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bathroom', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('storage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('parking', models.BooleanField(blank=True, null=True)),
                ('basement', models.BooleanField(blank=True, null=True)),
                ('view', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
