# Generated by Django 4.1.7 on 2023-03-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
