# Generated by Django 4.1.7 on 2023-03-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_image_url_property_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='basement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
