# Generated by Django 4.1.7 on 2023-03-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_basement_alter_property_parking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='yard_area',
            new_name='yardArea',
        ),
    ]
