# Generated by Django 4.1.7 on 2023-03-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_remove_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
