# Generated by Django 4.1.7 on 2023-03-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='imageUrl',
            field=models.ImageField(upload_to='properties'),
        ),
    ]
