# Generated by Django 4.1.7 on 2023-03-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_property_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='imageUrl',
            field=models.URLField(),
        ),
    ]
