# Generated by Django 4.1.7 on 2023-03-14 21:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('facebook', models.URLField()),
                ('email', models.URLField()),
                ('website', models.URLField()),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
